# Generated by Django 4.2.5 on 2023-09-26 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('quantity', models.IntegerField(default=0)),
                ('was_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=36)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(default=None, max_length=16)),
                ('address', models.CharField(default=None, max_length=256)),
                ('registered', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.user')),
                ('products', models.ManyToManyField(to='store.product')),
            ],
        ),
    ]
