# Generated by Django 4.2.5 on 2023-10-04 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_order_customer_remove_order_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproductcount',
            name='products',
        ),
        migrations.AddField(
            model_name='orderproductcount',
            name='products',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
    ]
