# Generated by Django 4.2.5 on 2023-10-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproductcount',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
